# Generated by Django 5.2.14 on 2026-05-23 09:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_number', models.IntegerField()),
                ('year_name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'سنة دراسية',
                'verbose_name_plural': 'السنوات الدراسية',
                'db_table': 'academicyears',
                'ordering': ['year_number'],
            },
        ),
        migrations.CreateModel(
            name='AlternativeTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(blank=True, max_length=255, null=True)),
                ('original_day', models.CharField(blank=True, choices=[('Saturday', 'السبت'), ('Sunday', 'الأحد'), ('Monday', 'الاثنين'), ('Tuesday', 'الثلاثاء'), ('Wednesday', 'الأربعاء'), ('Thursday', 'الخميس')], max_length=20, null=True)),
                ('original_time_start', models.TimeField(blank=True, null=True)),
                ('original_time_end', models.TimeField(blank=True, null=True)),
                ('day', models.CharField(choices=[('Saturday', 'السبت'), ('Sunday', 'الأحد'), ('Monday', 'الاثنين'), ('Tuesday', 'الثلاثاء'), ('Wednesday', 'الأربعاء'), ('Thursday', 'الخميس')], max_length=20)),
                ('time_start', models.TimeField(blank=True, null=True)),
                ('time_end', models.TimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('approved', 'موافق'), ('rejected', 'مرفوض')], default='pending', max_length=10)),
                ('is_expired', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'طلب تغيير موعد',
                'verbose_name_plural': 'طلبات تغيير المواعيد',
                'db_table': 'alternative_times',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_main', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'فرع',
                'verbose_name_plural': 'الفروع',
                'db_table': 'branches',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('program_type', models.CharField(max_length=50)),
                ('academic_program', models.CharField(blank=True, max_length=255)),
                ('total_semesters', models.IntegerField()),
            ],
            options={
                'verbose_name': 'قسم',
                'verbose_name_plural': 'الأقسام',
                'db_table': 'departments',
            },
        ),
        migrations.CreateModel(
            name='EmailSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smtp_host', models.CharField(max_length=255)),
                ('smtp_port', models.IntegerField(default=587)),
                ('smtp_username', models.CharField(max_length=255)),
                ('smtp_password', models.CharField(max_length=255)),
                ('from_email', models.EmailField(max_length=255)),
                ('from_name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'إعدادات البريد',
                'verbose_name_plural': 'إعدادات البريد',
                'db_table': 'email_settings',
            },
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(max_length=100, unique=True)),
                ('subject', models.CharField(max_length=255)),
                ('body_html', models.TextField()),
                ('body_text', models.TextField()),
                ('variables', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'قالب بريد',
                'verbose_name_plural': 'قوالب البريد',
                'db_table': 'email_templates',
            },
        ),
        migrations.CreateModel(
            name='PasswordReset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255)),
                ('token', models.CharField(max_length=255)),
                ('user_type', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'password_resets',
            },
        ),
        migrations.CreateModel(
            name='ScheduleDeadline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deadline_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'موعد نهائي',
                'verbose_name_plural': 'المواعيد النهائية',
                'db_table': 'schedule_deadlines',
            },
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=50)),
                ('established_year', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'جامعة',
                'verbose_name_plural': 'الجامعات',
                'db_table': 'universities',
            },
        ),
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=50)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colleges', to='timetable.branch')),
            ],
            options={
                'verbose_name': 'كلية',
                'verbose_name_plural': 'الكليات',
                'db_table': 'colleges',
            },
        ),
        migrations.CreateModel(
            name='UnifiedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('user_type', models.CharField(choices=[('student', 'طالب'), ('professor', 'أستاذ'), ('college_manager', 'مدير كلية'), ('system_manager', 'مدير النظام')], max_length=20)),
                ('user_id', models.IntegerField(default=0)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('college', models.ForeignKey(blank=True, db_column='college_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='timetable.college')),
                ('department', models.ForeignKey(blank=True, db_column='department_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='timetable.department')),
            ],
            options={
                'verbose_name': 'مستخدم',
                'verbose_name_plural': 'المستخدمون',
                'db_table': 'users_with_email',
            },
        ),
        migrations.CreateModel(
            name='DepartmentAcademicPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester_type', models.CharField(choices=[('1', 'الفصل الأول'), ('2', 'الفصل الثاني')], max_length=1)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='timetable.department')),
                ('year', models.ForeignKey(db_column='year_id', on_delete=django.db.models.deletion.CASCADE, to='timetable.academicyear')),
            ],
            options={
                'verbose_name': 'الفترة الأكاديمية',
                'verbose_name_plural': 'الفترات الأكاديمية',
                'db_table': 'department_academic_periods',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=20)),
                ('course_name', models.CharField(max_length=255)),
                ('lecture_hours', models.IntegerField(default=0)),
                ('exercise_hours', models.IntegerField(default=0)),
                ('lab_hours', models.IntegerField(default=0)),
                ('total_lectures', models.IntegerField(default=0)),
                ('is_shared_across_departments', models.BooleanField(default=False)),
                ('is_shared_across_colleges', models.BooleanField(default=False)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='timetable.departmentacademicperiod')),
            ],
            options={
                'verbose_name': 'مادة',
                'verbose_name_plural': 'المواد',
                'db_table': 'courses',
            },
        ),
        migrations.CreateModel(
            name='DepartmentStudentSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_count', models.IntegerField(default=0)),
                ('groups_count', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='timetable.department')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_settings', to='timetable.departmentacademicperiod')),
            ],
            options={
                'verbose_name': 'إعدادات طلاب القسم',
                'verbose_name_plural': 'إعدادات طلاب الأقسام',
                'db_table': 'department_student_settings',
            },
        ),
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50)),
                ('capacity', models.IntegerField()),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_halls', to='timetable.college')),
            ],
            options={
                'verbose_name': 'معمل',
                'verbose_name_plural': 'المعامل',
                'db_table': 'halls',
            },
        ),
        migrations.CreateModel(
            name='LectureChangeNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('request_approval', 'طلب موافقة'), ('approval_notification', 'إشعار موافقة'), ('rejection_notification', 'إشعار رفض')], max_length=30)),
                ('sent_to_manager', models.BooleanField(default=False)),
                ('sent_to_professor', models.BooleanField(default=False)),
                ('sent_to_students', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('alternative_time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.alternativetime')),
            ],
            options={
                'db_table': 'lecture_change_notifications',
            },
        ),
        migrations.CreateModel(
            name='LectureSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('Saturday', 'السبت'), ('Sunday', 'الأحد'), ('Monday', 'الاثنين'), ('Tuesday', 'الثلاثاء'), ('Wednesday', 'الأربعاء'), ('Thursday', 'الخميس')], max_length=15)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('lecture_type', models.CharField(choices=[('lecture', 'محاضرة'), ('exercise', 'تمرين')], default='lecture', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.course')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.department')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.departmentacademicperiod')),
            ],
            options={
                'verbose_name': 'جدول محاضرة',
                'verbose_name_plural': 'جداول المحاضرات',
                'db_table': 'lecture_schedule',
            },
        ),
        migrations.AddField(
            model_name='alternativetime',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='timetable.lectureschedule'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_type', models.CharField(blank=True, max_length=20, null=True)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('sent', 'مُرسَل'), ('failed', 'فشل')], default='pending', max_length=10)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(blank=True, db_column='recipient_id', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'إشعار',
                'verbose_name_plural': 'الإشعارات',
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('position', models.CharField(choices=[('أستاذ', 'أستاذ'), ('أستاذ مشارك', 'أستاذ مشارك'), ('محاضر', 'محاضر'), ('مساعد تدريس', 'مساعد تدريس'), ('دكتور', 'دكتور'), ('بروفيسور', 'بروفيسور')], max_length=50)),
                ('college', models.ForeignKey(db_column='college_id', on_delete=django.db.models.deletion.CASCADE, to='timetable.college')),
            ],
            options={
                'verbose_name': 'أستاذ',
                'verbose_name_plural': 'الأساتذة',
                'db_table': 'users',
            },
        ),
        migrations.AddField(
            model_name='lectureschedule',
            name='professor',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='timetable.professor'),
        ),
        migrations.CreateModel(
            name='LabSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('Saturday', 'السبت'), ('Sunday', 'الأحد'), ('Monday', 'الاثنين'), ('Tuesday', 'الثلاثاء'), ('Wednesday', 'الأربعاء'), ('Thursday', 'الخميس')], max_length=15)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('group_number', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.course')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.department')),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.hall')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.departmentacademicperiod')),
                ('assistant', models.ForeignKey(blank=True, db_column='assistant_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_assistant_schedules', to='timetable.professor')),
                ('professor', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='lab_schedules', to='timetable.professor')),
            ],
            options={
                'verbose_name': 'جدول معمل',
                'verbose_name_plural': 'جداول المعامل',
                'db_table': 'lab_schedule',
            },
        ),
        migrations.CreateModel(
            name='ExternalCollaborator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_university', models.CharField(max_length=255)),
                ('external_college', models.CharField(max_length=255)),
                ('external_department', models.CharField(blank=True, max_length=255, null=True)),
                ('specialization', models.CharField(blank=True, max_length=255, null=True)),
                ('academic_degree', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('professor', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='external_info', to='timetable.professor')),
            ],
            options={
                'db_table': 'external_collaborators',
            },
        ),
        migrations.AddField(
            model_name='alternativetime',
            name='professor',
            field=models.ForeignKey(db_column='professor_id', on_delete=django.db.models.deletion.CASCADE, to='timetable.professor'),
        ),
        migrations.CreateModel(
            name='ProfessorCollegeRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(choices=[('primary', 'أساسي'), ('collaboration', 'تعاون')], default='collaboration', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.college')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='college_relations', to='timetable.professor')),
            ],
            options={
                'db_table': 'professor_college_relations',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('full_name', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('مدير_نظام', 'مدير النظام'), ('مدير_كلية', 'مدير الكلية'), ('مساعد_مدير', 'مساعد المدير')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('college', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='timetable.college')),
            ],
            options={
                'verbose_name': 'صلاحية',
                'verbose_name_plural': 'الصلاحيات',
                'db_table': 'roles',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('capacity', models.IntegerField()),
                ('code', models.CharField(max_length=50)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_rooms', to='timetable.college')),
            ],
            options={
                'verbose_name': 'قاعة دراسية',
                'verbose_name_plural': 'القاعات الدراسية',
                'db_table': 'rooms',
            },
        ),
        migrations.AddField(
            model_name='lectureschedule',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.room'),
        ),
        migrations.AddField(
            model_name='alternativetime',
            name='original_room',
            field=models.ForeignKey(blank=True, db_column='original_room_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='original_requests', to='timetable.room'),
        ),
        migrations.AddField(
            model_name='alternativetime',
            name='room',
            field=models.ForeignKey(blank=True, db_column='room_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alternative_requests', to='timetable.room'),
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester_number', models.IntegerField()),
                ('semester_name', models.CharField(max_length=50)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('year', models.ForeignKey(db_column='year_id', on_delete=django.db.models.deletion.CASCADE, to='timetable.academicyear')),
            ],
            options={
                'verbose_name': 'فصل دراسي',
                'verbose_name_plural': 'الفصول الدراسية',
                'db_table': 'semesters',
            },
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specializations', to='timetable.department')),
                ('period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='timetable.departmentacademicperiod')),
            ],
            options={
                'verbose_name': 'تخصص',
                'verbose_name_plural': 'التخصصات',
                'db_table': 'specializations',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='specialization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='timetable.specialization'),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('specialization_id', models.IntegerField(default=0)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='timetable.department')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.departmentacademicperiod')),
            ],
            options={
                'verbose_name': 'طالب',
                'verbose_name_plural': 'الطلاب',
                'db_table': 'students',
            },
        ),
        migrations.CreateModel(
            name='TaughtLecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taught_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notification_sent', models.BooleanField(default=False)),
                ('professor', models.ForeignKey(db_column='professor_id', on_delete=django.db.models.deletion.CASCADE, to='timetable.professor')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.lectureschedule')),
            ],
            options={
                'verbose_name': 'محاضرة مُدَرَّسة',
                'verbose_name_plural': 'المحاضرات المُدَرَّسة',
                'db_table': 'taught_lectures',
            },
        ),
        migrations.AddField(
            model_name='branch',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='timetable.university'),
        ),
        migrations.CreateModel(
            name='CollegeDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.college')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.department')),
            ],
            options={
                'verbose_name': 'قسم الكلية',
                'verbose_name_plural': 'أقسام الكلية',
                'db_table': 'college_departments',
                'unique_together': {('college', 'department')},
            },
        ),
        migrations.CreateModel(
            name='CollegeHall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(choices=[('owner', 'مالك'), ('shared', 'مشارك')], default='owner', max_length=10)),
                ('added_by', models.IntegerField(blank=True, null=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.college')),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.hall')),
            ],
            options={
                'db_table': 'college_halls',
                'unique_together': {('college', 'hall')},
            },
        ),
        migrations.CreateModel(
            name='CollegeRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(choices=[('owner', 'مالك'), ('shared', 'مشارك')], default='owner', max_length=10)),
                ('added_by', models.IntegerField(blank=True, null=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.college')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.room')),
            ],
            options={
                'db_table': 'college_rooms',
                'unique_together': {('college', 'room')},
            },
        ),
    ]
