# Generated by Django 5.2.14 on 2026-05-23 12:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ScheduleChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_type', models.CharField(choices=[('lecture', 'محاضرة'), ('lab', 'معمل')], max_length=10)),
                ('schedule_id', models.IntegerField()),
                ('action', models.CharField(choices=[('add', 'إضافة'), ('edit', 'تعديل'), ('delete', 'حذف')], max_length=10)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('old_data', models.JSONField(blank=True, null=True)),
                ('new_data', models.JSONField(blank=True, null=True)),
                ('change_reason', models.TextField(blank=True, null=True)),
                ('department_name', models.CharField(blank=True, max_length=255, null=True)),
                ('course_name', models.CharField(blank=True, max_length=255, null=True)),
                ('changed_by', models.ForeignKey(blank=True, db_column='changed_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'سجل التغييرات',
                'verbose_name_plural': 'سجلات التغييرات',
                'db_table': 'schedule_change_log',
                'ordering': ['-changed_at'],
            },
        ),
    ]
