# Generated by Django 5.2.14 on 2026-05-23 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0002_add_changelog_and_notification_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alternativetime',
            name='is_expired',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='alternativetime',
            name='status',
            field=models.CharField(choices=[('pending', 'قيد الانتظار'), ('approved', 'موافق'), ('rejected', 'مرفوض')], db_index=True, default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='labschedule',
            name='day_of_week',
            field=models.CharField(choices=[('Saturday', 'السبت'), ('Sunday', 'الأحد'), ('Monday', 'الاثنين'), ('Tuesday', 'الثلاثاء'), ('Wednesday', 'الأربعاء'), ('Thursday', 'الخميس')], db_index=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='lectureschedule',
            name='day_of_week',
            field=models.CharField(choices=[('Saturday', 'السبت'), ('Sunday', 'الأحد'), ('Monday', 'الاثنين'), ('Tuesday', 'الثلاثاء'), ('Wednesday', 'الأربعاء'), ('Thursday', 'الخميس')], db_index=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='unifieduser',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='unifieduser',
            name='user_type',
            field=models.CharField(choices=[('student', 'طالب'), ('professor', 'أستاذ'), ('college_manager', 'مدير كلية'), ('department_head', 'رئيس قسم'), ('system_manager', 'مدير النظام')], db_index=True, max_length=20),
        ),
        migrations.AddIndex(
            model_name='labschedule',
            index=models.Index(fields=['day_of_week', 'start_time', 'end_time'], name='lab_day_time_idx'),
        ),
        migrations.AddIndex(
            model_name='labschedule',
            index=models.Index(fields=['professor', 'day_of_week'], name='lab_prof_day_idx'),
        ),
        migrations.AddIndex(
            model_name='labschedule',
            index=models.Index(fields=['department', 'period'], name='lab_dept_period_idx'),
        ),
        migrations.AddIndex(
            model_name='lectureschedule',
            index=models.Index(fields=['day_of_week', 'start_time', 'end_time'], name='lec_day_time_idx'),
        ),
        migrations.AddIndex(
            model_name='lectureschedule',
            index=models.Index(fields=['professor', 'day_of_week'], name='lec_prof_day_idx'),
        ),
        migrations.AddIndex(
            model_name='lectureschedule',
            index=models.Index(fields=['department', 'period'], name='lec_dept_period_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'is_read'], name='notif_recipient_read_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', '-created_at'], name='notif_recipient_date_idx'),
        ),
    ]
